project_id = "devops-demo-4569"
namespace  = "devops-demo"
region     = "asia-east1"
support_email = "yitingli.public@gmail.com"
credentials = "/home/xexanoth/.config/gcloud/application_default_credentials.json"